def upload_to_youtube(video_path: str):
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request
    import os, pickle

    SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

    # Путь к секретному файлу
    CLIENT_SECRETS_FILE = "/etc/secrets/client_secrets.json"

    creds = None
    if os.path.exists("token.pickle"):
        with open("token.pickle", "rb") as token:
            creds = pickle.load(token)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS_FILE, SCOPES)
            creds = flow.run_console()

        with open("token.pickle", "wb") as token:
            pickle.dump(creds, token)

    youtube = build("youtube", "v3", credentials=creds)

    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": "AI Stylized Short",
                "description": "Generated by AI Video Stylizer Server",
                "tags": ["AI", "shorts", "stylizer"],
                "categoryId": "22"  # People & Blogs
            },
            "status": {"privacyStatus": "public"}
        },
        media_body=MediaFileUpload(video_path)
    )
    response = request.execute()
    print("✅ Uploaded to YouTube:", response.get("id"))
